# Generated by Django 3.2.8 on 2021-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='oldrating',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
